### ISSUE TITLE
Add issue template

### ISSUE THREAD

**Issue by gcochard** [spectcl/spectcl#107]
1. Create file named `issue_template.md` (and maybe one named `pull_request_template.md`)
2. Check this in
3. Create PR
4. Merge
5. ...
6. Profit!

Background: https://github.com/dear-github/dear-github/issues/125

**Comment by gcochard** [comment]
Officially documented: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by ryanbmilbourne** [comment]
We should definitely use the Pull Request templates.

**Comment by gcochard** [comment]
Let's start a PR template here

**Comment by gcochard** [comment]
And an issue template here


# Description of the bad behavor
# Description of how to reproduce the problem
> If the issue resulted in a crash, stack-trace in a block quote here
# Description of the expected behavior

**Comment by ryanbmilbourne** [comment]
Added version to issue template comment place-holder.

**Comment by ryanbmilbourne** [comment]
Started off the PR template.

**Comment by gcochard** [comment]
# Issue template latest version <br><br><br><br><br>


## Description of the bad behavor
## Version of `spectcl` showing said bad behavior
## Description of how to reproduce the problem

Spectcl has crashed! 
```
stack-trace here
```

## Description of the expected behavior

**Comment by gcochard** [comment]
# PR template latest version<br><br><br><br>

## What does this Pull Request do?

## Where should the maintainers start when reviewing your request?

## Is there any additional background context you'd like to provide?

## Are there any relevant issues?
#1234

## Questions:
- Does this request add new dependencies to `spectcl`?
- Does this request constitute a MAJOR change to `spectcl`'s version?

**Comment by gcochard** [comment]
Good to go?

**Comment by ryanbmilbourne** [comment]
:+1: :shipit:
