### ISSUE TITLE
Obtain `pty` before spawning child

### ISSUE THREAD

**Issue by ryanbmilbourne** [spectcl/spectcl#16]
> When a process is spawned, Expect allocates the pty, creates the process, and arranges for the process to use the pty for its standard input among other things.
*Libes, Exploring Expect: A Tcl-based Toolkit for Automating Interactive Programs, p294*

`nexpect` only spawns the child session.  Spectcl in its current state does the same.  As a result, children like `ssh`, who rely on a pty, complain and aren't workable under the current model of child spawning.  We should modify spectcl to obtain the pty for the process before spawning.

**Comment by ryanbmilbourne** [comment]
After evaluating a few packages, I'm going to start working with [child_pty](https://github.com/Gottox/child_pty).  
I like that it borrows heavily from and acts as a `child_process` rather than defining a new structure like [pty.js](https://github.com/chjj/pty.js) does.  I also had issues with `pty.js` and its error handling.  See https://github.com/chjj/pty.js/issues/34.

I also want to vary from TCL Expect and implement a `no-pty` option.  With concurrent sessions hosting, for example, telnet connections, that many ptys would add unnecessary system overhead.  Thoughts, @gcochard?

**Comment by gcochard** [comment]
:+1: sounds like a good plan. I would just verify that the `columns` option can be set to 0 to indicate that lines should not wrap.

**Comment by ryanbmilbourne** [comment]
The downside is going to be that I cannot build `child_pty` on Node v0.10.x and it looks like the maintainer does not support v.0.10.x anymore.  We'd have to support v0.12.x+ rather than v0.10.x+.  I don't think that's an issue, considering the age of v0.10.x and the recent release of v4.0.0.  Do you concur?

**Comment by ryanbmilbourne** [comment]
Waiting on fix for Gottox/child_pty#9 before continuing.

**Comment by ryanbmilbourne** [comment]
`child_pty` is now at v2.0.1 in npm and includes the fix for aforementioned issue.  :+1:

**Comment by gcochard** [comment]
Protip: If you put "Fixes #16" on your commit message, it will auto-close on merge.

**Comment by ryanbmilbourne** [comment]
`Resolves:` should have closed the issue...not sure why it did not.  IIRC `resolves` is synonymic to `fixes`...

**Comment by gcochard** [comment]
Must be a bug. Maybe it has to be in the latest commit, or in the commit summary. Let's standardize on what eslint is doing, making it in the summary in parens.

**Comment by gcochard** [comment]
Also, thoughts on squashing into one commit pre-merge? I'm for it as it maintains a clean history with each commit representing a buildable, tests-passing state.

**Comment by ryanbmilbourne** [comment]
Personally, I prefer more [atomic](http://www.freshconsulting.com/atomic-commits/) commits so that it's easier to back out individual changes, rather than an entire pull requests' worth.  

That's not to say that commits should break code, rather they should represent a complete block of work on a given issue or task.  Perhaps a good middle ground would be to squash work on related issues together.  Squashing PRs to one commit as a blanket policy could make it difficult to roll out issues if a PR fixes multiple issues/tasks.
