### ISSUE TITLE
session instanceof Spectcl !== true 

### ISSUE THREAD

**Issue by gcochard** [spectcl/spectcl#41]
When creating a new spectcl object, it appears it does not return an instance of `Spectcl`. Looks like instead of returning an object literal on line 25, we need to restructure to init vars in the `Spectcl` constructor, and add prototype methods for all of the callable methods on it.

**Comment by gcochard** [comment]
The fix could also be to just not use `new`, as [many](http://stackoverflow.com/questions/383402/is-javascripts-new-keyword-considered-harmful) [consider it](http://www.ianbicking.org/blog/2013/04/new-considered-harmful.html) [harmful](http://yuiblog.com/blog/2006/11/13/javascript-we-hardly-new-ya/).

We should ensure that multiple "instances" of spectcl play nicely together.

**Comment by ryanbmilbourne** [comment]
Sorry, it turns out I had accidentally unwatched `spectcl` and didn't see this issue until now.  I'll look into it.

> We should ensure that multiple "instances" of spectcl play nicely together, regardless of the fix.

I agree.  That's one of the central points of the module.

**Comment by ryanbmilbourne** [comment]
I have this scheduled in my next sprint.
